# -*- coding: utf-8 -*-
"""Week 3_SIT782.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RVjc9nZVhLBNXS2rKUPs86_QNuUvL_4

### Student Name: Abin Baby
### Student Id: 224640656

## Loading and understanding dataset
"""

import pandas as pd
df = pd.read_csv("phoenix_synthetic_dataset_2024.csv")
print(df.head())
print(df.info())
print(df.describe())

"""## Basic exploration"""

import matplotlib.pyplot as plt
import pandas as pd
# Convert date correctly
df['date'] = pd.to_datetime(df['date'], dayfirst=True)

# Plot cyber incidents over time
plt.figure(figsize=(10,5))
plt.plot(df['date'], df['cyber_incidents'])
plt.xticks(rotation=45)
plt.title("Cyber Incidents Over Time")
plt.xlabel("Date")
plt.ylabel("Incidents")
plt.show()

"""## Relationship between hazard and cyber incidents"""

import seaborn as sns
plt.figure()
sns.boxplot(x='hazard_level', y='cyber_incidents', data=df)
plt.title("Cyber Incidents by Hazard Level")
plt.show()

"""## Correlation analysis"""

plt.figure()
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True)
plt.title("Correlation Matrix")
plt.show()

"""## Anomaly Detection"""

from sklearn.ensemble import IsolationForest

features = df[['cyber_incidents', 'phishing_reports', 'misinformation_reports']]

model = IsolationForest(contamination=0.05, random_state=42)
df['anomaly'] = model.fit_predict(features)

# Show anomalies
anomalies = df[df['anomaly'] == -1]
print(anomalies)

"""## Visualise anomalies"""

plt.figure()
plt.scatter(df['date'], df['cyber_incidents'], label='Normal')
plt.scatter(anomalies['date'], anomalies['cyber_incidents'], label='Anomaly')
plt.legend()
plt.title("Anomaly Detection in Cyber Incidents")
plt.xticks(rotation=45)
plt.show()